### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by antoniobrandao** [EvolveLabs/electron-updater-sample#4]
Followed all the steps, but get this result:

```
19:41 ~/electron-updater-example/ electron .
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/antoniobrandao/WEBROOT/eus/main.js:1:90)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)    
```

**Comment by justinmchase** [comment]
Sadly there is a Pull Request pending that I don't have permissions to accept: https://github.com/EvolveLabs/electron-updater-sample/pull/2

I believe someone made a fork with the fix that you can use.
