### ISSUE TITLE
run electron . has a error,

### ISSUE THREAD

**Issue by jeffycai** [EvolveLabs/electron-updater-sample#5]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\AppData\Roaming\npm\node_modules.electron-prebuilt_npminstall\electron-prebuilt\1.4.3\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Desktop\electron\updater\main.js:1:90)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

[确定]

**Comment by justinmchase** [comment]
There is a pending PR that fixes this that I don't have permissions to merge #2
